import type { Metadata } from "next";
import Link from "next/link";
import { DM_Sans, Instrument_Serif } from "next/font/google";
import { MapEmbed } from "@/components/demo/MapEmbed";
import { VibeLabBar } from "@/components/demo/VibeLabBar";
import { menuCategories } from "./data";

const sans = DM_Sans({ subsets: ["latin", "latin-ext"], display: "swap", variable: "--font-skadar-sans" });
const serif = Instrument_Serif({ weight: "400", subsets: ["latin"], display: "swap", variable: "--font-skadar-serif" });
export const metadata: Metadata = { title: "Konoba Skadar — Virpazar | Dizajn koncept", description: "Dizajn koncept za konobu u Virpazaru sa jelovnikom, rezervacijama i lokacijom.", robots: { index: false, follow: false }, openGraph: { images: ["/og-demo-konoba-skadar.png"] } };
const label = "text-[10px] font-bold tracking-[0.16em] uppercase";
const focus = "focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#c95f37]";
const primary = `inline-flex min-h-12 items-center justify-center bg-[#173b34] px-6 text-sm font-bold text-[#f7f6f0] transition-colors hover:bg-[#c95f37] ${focus}`;

export default function KonobaSkadarPage() {
  return <div className={`${sans.variable} ${serif.variable} konoba-skadar-concept min-h-screen bg-[#f7f6f0] pb-20 text-[#173b34] [font-family:var(--font-skadar-sans)] md:pb-0`}>
    <VibeLabBar />
    <header className="border-b border-[#173b34]/15 bg-[#f7f6f0]"><div className="mx-auto flex max-w-6xl items-center justify-between gap-5 px-5 py-4 sm:px-8"><a href="#vrh" className={`text-lg font-bold tracking-[-0.06em] ${focus}`}>Konoba Skadar</a><nav aria-label="Glavna navigacija" className="hidden items-center gap-6 md:flex"><a href="#jelovnik" className={`${label} hover:text-[#c95f37] ${focus}`}>Jelovnik</a><a href="#prica" className={`${label} hover:text-[#c95f37] ${focus}`}>O nama</a><a href="#rezervacije" className={`${label} hover:text-[#c95f37] ${focus}`}>Rezervacije</a></nav><a href="tel:+38267000000" className={`hidden min-h-10 items-center bg-[#173b34] px-4 text-xs font-bold text-white hover:bg-[#c95f37] sm:inline-flex ${focus}`}>Rezerviši sto</a></div></header>
    <main id="vrh">
      <section className="overflow-hidden border-b border-[#173b34]/15"><div className="mx-auto grid max-w-6xl gap-10 px-5 py-14 sm:px-8 sm:py-20 lg:grid-cols-[1.1fr_.9fr] lg:items-end"><div><p className={`${label} text-[#c95f37]`}>Virpazar · Skadarsko jezero</p><h1 className="mt-5 max-w-3xl text-5xl leading-[.87] tracking-[-0.07em] sm:text-7xl lg:text-8xl">Sto uz jezero.<br /><span className="font-[family-name:var(--font-skadar-serif)] tracking-[-0.04em]">Ukusi koji ostaju.</span></h1><p className="mt-7 max-w-lg text-base leading-relaxed text-[#173b34]/70 sm:text-lg">Riba iz jezera, domaća kuhinja i vino iz Crmnice. Bez žurbe — samo dobar sto i pogled koji zaslužuje još jednu čašu.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><a href="tel:+38267000000" className={primary}>Rezerviši sto <span aria-hidden="true" className="ml-5">↗</span></a><a href="#jelovnik" className={`inline-flex min-h-12 items-center justify-center border border-[#173b34]/25 px-6 text-sm font-bold hover:border-[#173b34] ${focus}`}>Pogledaj jelovnik</a></div></div><div aria-hidden="true" className="relative h-64 overflow-hidden bg-[#d9e1d8] sm:h-80"><div className="absolute -bottom-24 -left-10 h-64 w-[125%] rounded-[50%] border-[22px] border-[#6e8b82]"/><div className="absolute -bottom-36 left-14 h-64 w-[110%] rounded-[50%] border-[22px] border-[#173b34]"/><div className="absolute right-8 top-8 h-16 w-16 rounded-full bg-[#e9a04c]"/><p className="absolute bottom-7 left-7 text-xs font-bold tracking-[.14em] text-white uppercase">Tiha voda, dobar sto</p></div></div></section>
      <section id="jelovnik" className="scroll-mt-6 bg-[#edf0e9]"><div className="mx-auto max-w-6xl px-5 py-16 sm:px-8 sm:py-24"><div className="grid gap-5 border-b border-[#173b34]/15 pb-8 md:grid-cols-2 md:items-end"><div><p className={`${label} text-[#c95f37]`}>Jelovnik</p><h2 className="mt-3 text-4xl tracking-[-0.065em] sm:text-5xl">Ono što bismo i sami naručili.</h2></div><p className="max-w-sm text-sm leading-relaxed text-[#173b34]/65 md:justify-self-end">Jezerska riba, jela ispod sača i lokalne stvari koje idu najbolje uz duži razgovor.</p></div><div className="mt-8 grid gap-x-12 lg:grid-cols-2">{menuCategories.map((category, index) => <details key={category.id} className="group border-b border-[#173b34]/15" open={index === 0}><summary className="flex min-h-16 cursor-pointer list-none items-center justify-between gap-5 py-4 [&::-webkit-details-marker]:hidden"><span className="text-xl font-bold tracking-[-.04em]">{category.title}</span><span aria-hidden="true" className="text-xl text-[#c95f37] transition-transform group-open:rotate-45">+</span></summary><ul className="space-y-5 pb-7">{category.items.map((item) => <li key={item.name}><div className="grid grid-cols-[minmax(0,1fr)_auto] items-baseline gap-5"><h3 className="font-bold">{item.name}</h3><span className="font-bold tabular-nums">{item.price}</span></div><p className="mt-1 text-sm leading-relaxed text-[#173b34]/65">{item.description}</p></li>)}</ul></details>)}</div><p className="mt-7 text-xs text-[#173b34]/55">Ilustrativni jelovnik i cijene za potrebe koncepta — potvrditi prije objave.</p></div></section>
      <section id="prica" className="scroll-mt-6"><div className="mx-auto grid max-w-6xl gap-12 px-5 py-16 sm:px-8 sm:py-24 lg:grid-cols-[.75fr_1.25fr]"><div><p className={`${label} text-[#c95f37]`}>Naš način</p><h2 className="mt-3 text-4xl leading-[.95] tracking-[-.065em] sm:text-5xl">Ne komplikujemo ono što je već dobro.</h2></div><div className="max-w-2xl"><p className="font-[family-name:var(--font-skadar-serif)] text-3xl leading-[1.04] tracking-[-.035em] sm:text-4xl">Mjesto za ručak poslije vožnje jezerom, večeru s porodicom ili sto koji se ne napušta kad padne sunce.</p><div className="mt-9 grid gap-7 border-t border-[#173b34]/15 pt-6 sm:grid-cols-3">{[["Jezero", "Riba i ukljeva kad je svježa."],["Crmnica", "Vino koje pripada ovom kraju."],["Domaće", "Recepti bez suvišnih riječi."]].map(([title, body]) => <div key={title}><h3 className="font-bold">{title}</h3><p className="mt-2 text-sm leading-relaxed text-[#173b34]/65">{body}</p></div>)}</div></div></div></section>
      <section id="rezervacije" className="scroll-mt-6 bg-[#173b34] text-[#f7f6f0]"><div className="mx-auto grid max-w-6xl gap-10 px-5 py-16 sm:px-8 sm:py-24 lg:grid-cols-2"><div><p className={`${label} text-[#f0a984]`}>Rezervacije</p><h2 className="mt-3 max-w-md text-4xl tracking-[-.065em] sm:text-5xl">Sačuvaj sebi dobar sto.</h2><p className="mt-5 max-w-md text-sm leading-relaxed text-white/65">Za terasu, ručak za više ljudi ili poseban datum — pozovite nas malo ranije.</p><a href="tel:+38267000000" className={`mt-8 inline-flex min-h-12 items-center justify-center bg-[#f7f6f0] px-6 text-sm font-bold text-[#173b34] hover:bg-[#f0a984] ${focus}`}>+382 67 000 000</a></div><div className="grid content-end gap-0 border-t border-white/20 sm:grid-cols-3 sm:border-t-0">{[["01", "Pozovite", "Datum, vrijeme i broj gostiju."],["02", "Potvrdimo", "Javljamo vam da je sto vaš."],["03", "Uživajte", "Ostalo je na nama."]].map(([number,title,body]) => <div key={number} className="border-b border-white/20 py-5 sm:border-b-0 sm:border-l sm:px-5 sm:first:border-l-0 sm:first:pl-0"><p className={`${label} text-[#f0a984]`}>{number}</p><h3 className="mt-4 font-bold">{title}</h3><p className="mt-2 text-sm leading-relaxed text-white/60">{body}</p></div>)}</div></div></section>
      <section id="lokacija" className="scroll-mt-6 bg-[#e3e8df]"><div className="mx-auto grid max-w-6xl gap-10 px-5 py-16 sm:px-8 sm:py-24 lg:grid-cols-2"><div><p className={`${label} text-[#c95f37]`}>Lokacija</p><h2 className="mt-3 text-4xl tracking-[-.065em] sm:text-5xl">Obala 13,<br />Virpazar.</h2><address className="mt-7 not-italic text-sm leading-relaxed"><strong>Obala 13, 81305 Virpazar, Crna Gora</strong><br /><span className="text-[#173b34]/65">Ponedjeljak–Nedjelja · 10:00–23:00</span></address><a href="viber://chat?number=%2B38267000000" className={`mt-8 inline-flex text-sm font-bold underline decoration-[#c95f37] decoration-2 underline-offset-4 ${focus}`}>Pošalji poruku na Viber</a></div><div className="overflow-hidden border border-[#173b34]/20 bg-white p-1.5"><MapEmbed query="Obala 13, 81305 Virpazar, Crna Gora" title="Mapa — Obala 13, 81305 Virpazar, Crna Gora" className="h-72 w-full border-0 grayscale-[25%] sm:h-full sm:min-h-80" buttonClassName={`${primary} px-5 text-sm`} linkClassName={`text-xs underline underline-offset-4 ${focus}`} /></div></div></section>
    </main><footer className="bg-[#12332d] text-[#f7f6f0]"><div className="mx-auto flex max-w-6xl flex-col gap-4 px-5 py-10 sm:flex-row sm:items-end sm:justify-between sm:px-8"><p className="text-lg font-bold tracking-[-.06em]">Konoba Skadar</p><p className="text-xs text-white/60">Koncept: <Link href="/" className={`font-bold text-white hover:text-[#f0a984] ${focus}`}>VibeLab</Link></p></div></footer><a href="tel:+38267000000" className={`fixed inset-x-4 bottom-4 z-50 inline-flex min-h-14 items-center justify-center bg-[#173b34] px-5 text-sm font-bold text-white shadow-xl md:hidden ${focus}`}>Rezerviši sto</a>
  </div>;
}
